#web服务器配置
server:
  port: 80  #优先级低于application.properties当中的server.port=8866
#springboot配置
spring:
  #开发环境dev，测试环境test，生产环境pro
  profiles:
    active: dev
  #数据库链接配置
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/moocdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver  #默认会根据url识别
    #Hikari配置
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: Hikarii
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #配置模板引擎
  thymeleaf:
    cache: false
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  #其实不用写，看源码，默认就是这几个，ssm配置习惯了
  resources:
    static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - classpath:/upload/

#配置分页工具
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false  #pageSize=0

#配置mybatis
mybatis-plus:
  #必须要有，为了配置xml文件中resultType返回值的包位置，如果未配置请在<mapper namespace>使用全包名com.***.***.pojo.***（mybatis）
  type-aliases-package: com.example.springdatajdbc.pojo
  #必须要有，寻找mapper xml配置文件，指定sql映射文件(mybatis)
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名法的理解支持
  configuration:
    map-underscore-to-camel-case: true
    #mybatis-plus的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





